---
- name: install Apache
  hosts: all
  gather_facts: false
  tasks: 
  - name: install debian Apache
    apt:
      name: apache2	  
      state: latest
  - service:
      name: apache2
      enabled: yes
  